# Generated by Django 3.1.3 on 2020-11-05 10:58

from django.db import migrations
import user_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_auto_20201105_1054'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_auth.models.UserManager()),
            ],
        ),
    ]
