# Generated by Django 3.1.3 on 2020-11-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20201105_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=100, verbose_name='username'),
            preserve_default=False,
        ),
    ]
